#!/bin/sh

set -e

lb config noauto \
	--apt apt \
	--architectures i386 \
	--apt-recommends false \
	--archive-areas "main contrib non-free" \
	--binary-images iso-hybrid \
	--clean \
	--debian-installer live \
	--debian-installer-distribution stretch \
	--debian-installer-gui true \
	--iso-publisher moihack \
	--distribution stretch \
	--firmware-binary true \
	--firmware-chroot true \
	--ignore-system-defaults \
	--mode debian \
	--system live \
	--linux-packages "linux-image linux-headers" \
	--win32-loader true \
"${@}"
